### ISSUE TITLE
Good use of numpy's where

### ISSUE THREAD

**Issue by Caealana** [ddd-fun/intro-data-capstone-musclehub#3]
<img width="537" alt="screenshot at may 13 10-26-59" src="https://user-images.githubusercontent.com/14001120/39968260-3c598052-5698-11e8-9b19-f1bc5ade699b.png">

You used numpy's where function well to create ab_test_group. This is just for your reference, but another method to create ab_test_group is using a lambda and pandas' .apply() function:
```
df['ab_test_group'] = df.fitness_test_date.apply(lambda x:
                                                'A' if pd.notnull(x) else 'B')
```

**Comment by ddd-fun** [comment]
Thanks a lot for lambda reference. 
With this code I've just explored numpy lib.
