### ISSUE TITLE
Contingency Table Mismatch

### ISSUE THREAD

**Issue by Caealana** [ddd-fun/intro-data-capstone-musclehub#4]
<img width="586" alt="screenshot at may 13 10-38-36" src="https://user-images.githubusercontent.com/14001120/39968375-ce930168-5699-11e8-9475-b07a799e30a4.png">

The correct answer for the contingency table comparing membership purchases between the two groups is:
`contingency = [[200, 50], [250, 75]]
`
It looks like in your second row you accidentally used the total number of members+not_members instead of only the number of people who are not members for the B group.

**Comment by ddd-fun** [comment]
oh.. yeah.. thanks for letting me know. 
Having fixed it, I got p-value around 0.4, which is still not enough to reject null hypo. Thus, overall outcome for business remained the same.
